#!/usr/bin/python3
#SPDH-FileCopyrightText: 2024   Itsuki Terasawa
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
        ans += tonum(line)
        
print(ans)
